version: "3.8"

services:
    mysql:
        image: arm64v8/mysql
        container_name: class_offline_db
        environment:
            MYSQL_ROOT_PASSWORD: 25042002
            MYSQL_DATABASE: class_offline
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    app:
        build: .
        image: class_offline_app
        container_name: class_offline
        ports:
            - "3000:3000"
        depends_on:
            - mysql
        environment:
            DB_HOST: class_offline_db
            DB_USER: root
            DB_PASSWORD: 25042002
            DB_NAME: class_offline
        volumes:
            - .:/app
        command: sh -c "npm install && npm run database && npm start"
volumes:
    db_data:
