name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull latest code on server
        run: |
          ssh -o StrictHostKeyChecking=no root@14.225.36.229 "
          cd /var/www/sites/Class_offline_Project/ && 
          git pull origin main &&
          "
